apiVersion: batch/v1
kind: Job
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  template:
    # This is the pod template
    spec:
      containers:
        - name: frontend
          image: TBA
          command: []
        restartPolicy: OnFailure
    # The pod template ends here
