apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: johncheng-ingress
  namespace: johncheng-prod
  labels:
    app: johncheng-ingress
spec:
  # tls:
  #   - hosts:
  #       - johncheng.me
  #     secretName: johncheng-prod-tls # Name of the TLS config
  rules:
    - host: local.johncheng.me
      http:
        paths:
          - path: /*
            backend:
              serviceName: johncheng-load-balancer
              servicePort: 80
